# Generated by Django 5.1.1 on 2024-10-29 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_products_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supercategory',
            name='slug',
        ),
    ]
